---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart tlsrep-proxy
  ansible.builtin.systemd_service:
    name: tlsrep-proxy
    state: restarted
    daemon_reload: true
